# Extended docker-compose configuration for Claude Code development
# Usage: docker-compose -f docker-compose.yml -f docker-compose.claude.yml up -d

services:
  aimeup-dev:
    # Use the Claude-specific Dockerfile with path fixes
    build:
      context: .
      dockerfile: Dockerfile.claude
      args:
        BUILDKIT_INLINE_CACHE: 1

    # Extend environment with API keys and Git configuration
    environment:
      # Pass through API keys from host environment (with empty defaults to avoid warnings)
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      LINEAR_API_KEY: ${LINEAR_API_KEY:-}
      # Git configuration
      GIT_USER_NAME: ${GIT_USER_NAME:-}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL:-}
      # Existing Expo configuration from base
      EXPO_DEVTOOLS_LISTEN_ADDRESS: '0.0.0.0'

    # Ensure working directory is /aimeup
    working_dir: /aimeup

    # Run as aimedev user (UID 501) to match host permissions
    user: aimedev

    # Load environment variables from .env file
    env_file:
      - .env

    # Add volume for Claude Code persistence
    volumes:
      # Inherit all volumes from base docker-compose.yml
      - ./:/aimeup
      - aimeup_node_modules:/aimeup/node_modules
      - pnpm_store:/home/aimedev/.local/share/pnpm/store
      # Use bind mount for Claude config persistence (matching main docker-compose.yml)
      - ./.claude-docker:/home/aimedev/.claude
      # Add bind mount for Cursor server with proper permissions
      - ./.cursor-server-docker:/home/aimedev/.cursor-server
# No additional volumes needed - using bind mount from main docker-compose.yml
