services:
  aimeup-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Bind mount source code for real-time synchronization
      - ./:/aimeup
      # Use named volume for node_modules for better performance on macOS
      - aimeup_node_modules:/aimeup/node_modules
      # Use named volume for pnpm cache
      - pnpm_store:/root/.local/share/pnpm/store
    # Keep container running so developers can exec into it
    command: tail -f /dev/null
    # Port mapping for Expo and development servers
    ports:
      # Expo web server
      - '8081:8081'
      # Expo DevTools range
      - '19000-19006:19000-19006'
    # Environment variables for Expo configuration
    environment:
      # Ensure Expo server binds to all interfaces for external access
      EXPO_DEVTOOLS_LISTEN_ADDRESS: '0.0.0.0'

volumes:
  # Named volumes for better performance
  aimeup_node_modules:
  pnpm_store:
